config/routes.rb
Rails.application.routes.draw do
  resources :builds
  root to: "home#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :maps
  resources :talents
  resources :heros
end

app/models/talent.rb
class Talent < ApplicationRecord
  has_many :hero_talents, inverse_of: :talent
  has_many :heros, through: :hero_talents

  has_many :build_talents, inverse_of: :talent
  has_many :builds, through: :build_talents

  mount_uploader :image, ImageUploader
end

app/controllers/talents_controller.rb
class TalentsController < ApplicationController
  before_action :set_talent, only: [:show, :edit, :update, :destroy]

  # GET /talents
  # GET /talents.json
  def index
    @talents = Talent.all
  end

  # GET /talents/1
  # GET /talents/1.json
  def show
  end

  # GET /talents/new
  def new
    @talent = Talent.new
    @heros = Hero.all
  end

  # GET /talents/1/edit
  def edit
    @heros = Hero.all
  end

  # POST /talents
  # POST /talents.json
  def create
    # params[:talent][:hero_talents_attributes].reject! {|k,v| p v["hero_id"] == '0'}
    @talent = Talent.new(talent_params)

    respond_to do |format|
      if @talent.save
        format.html { redirect_to @talent, notice: 'Talent was successfully created.' }
        format.json { render :show, status: :created, location: @talent }
      else
        format.html { render :new }
        format.json { render json: @talent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /talents/1
  # PATCH/PUT /talents/1.json
  def update
    respond_to do |format|
      if @talent.update(talent_params)
        format.html { redirect_to @talent, notice: 'Talent was successfully updated.' }
        format.json { render :show, status: :ok, location: @talent }
      else
        format.html { render :edit }
        format.json { render json: @talent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talents/1
  # DELETE /talents/1.json
  def destroy
    @talent.destroy
    respond_to do |format|
      format.html { redirect_to talents_url, notice: 'Talent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talent
      @talent = Talent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def talent_params
      params.require(:talent).permit(:name, :level, :description, :image, hero_ids: [])
    end
end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/views/talents/_form.html.erb
<div class='row'>
  <%= form_with(model: talent, local: true, class: 'form-horizontal form-material') do |form| %>
    <div class="col-md-4 col-xs-12">
      <div class="white-box">
        <div class="user-bg">
          
          <div class="overlay-box">
            <div class="user-content">
              <a href="javascript:void(0)">
                <%= image_tag talent.image_url(:thumb), class: 'thumb-lg img-circle' if talent.image? %>
              </a>
              <h4 class="text-white"><%= talent.name %></h4>
              <div class="text-center">
                <div class="col-sm-8 col-sm-offset-2">
                  <%= form.file_field :image %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-8 col-xs-12">
      <div class="white-box">

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control', placeholder: 'Name' %>
      </div>

      <div class="form-group">
        <%= form.label :level %>
        <%= form.text_field :level, class: 'form-control', placeholder: 'Level' %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control', placeholder: 'Description' %>
      </div>

      
      <div class="form-group">
        <%= form.label :hero_link, class: 'col-sm-12' %>
        <div class="col-sm-12">
          <%= form.collection_check_boxes :hero_ids, Hero.all, :id, :name do |b| %>
            <div class="row" style='margin:0;'>
              <%= b.label(class: "check_box") do %>
                <div style='width:2%;float:left;'>
                  <%= b.check_box(class: "check_box") %>
                </div>

                <div class="col-xs-8" style='padding:0;'>
                  <%= b.object.name %>
                </div>       
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <%= form.submit 'Submit', class: 'btn btn-default' %>

      </div>
    </div>
  <% end %>
</div>

app/views/talents/edit.html.erb
<%= render "layouts/page_title" %>

<%= render 'form', talent: @talent %>

<%= link_to 'Show', @talent %> |
<%= link_to 'Back', talents_path %>

app/views/talents/index.html.erb
<%= render "layouts/page_title" %>
<div class='row'>
  <div class='col-xs-12 text-right'>
    <%= link_to 'New Talent', new_talent_path, class: 'btn btn-sm btn-primary' %> 
  </div>
  <% @talents.each do |talent| %>
    <div class="col-sm-3">
      <div class="thumbnail">
        <%= image_tag talent.image_url(:thumb), class: 'thumb-lg img-circle' if talent.image? %>
        <div class="caption text-center">
          <h4 class='text-center'><%= talent.name %></h4>
          <p>
            <%= link_to 'View', talent, class: 'btn btn-sm btn-primary' %>
            <%= link_to 'Edit', edit_talent_path(talent), class: 'btn btn-sm btn-default' %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div> 

app/views/talents/new.html.erb
<%= render "layouts/page_title" %>

<%= render 'form', talent: @talent %>

<%= link_to 'Back', talents_path %>

app/views/talents/show.html.erb
<%= render "layouts/page_title" %>

<div class='row'>
  <div class="col-md-4 col-xs-12">
    <div class="white-box">
      <div class="user-bg">
        <div class="overlay-box">
          <div class="user-content">
            <a href="javascript:void(0)">
              <%= image_tag @talent.image_url(:thumb), class: 'thumb-lg img-circle' if @talent.image? %>
            </a>
            <h4 class="text-white">
              <%= @talent.name %> 
            </h4>
          </div>
        </div>
      </div>
      <div class="user-btm-box">
        <div class="col-sm-12 text-center">
          <p class="text-purple"><%= simple_format @talent.description %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-8 col-xs-12">
    <div class="white-box">
      <div class="row">
        <h3>Heros:</h3>
        <% @talent.heros.each do |hero| %>
          <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
              <%= image_tag hero.image_url(:thumb), class: 'thumb-lg img-circle' if hero.image? %>
              <div class="caption">
                <h4 class='text-center'><%= hero.name %></h4>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>