config/routes.rb
Rails.application.routes.draw do
  resources :builds
  root to: "home#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :maps
  resources :talents
  resources :heros
end

app/models/hero.rb
class Hero < ApplicationRecord
  has_many :hero_talents, inverse_of: :hero
  has_many :talents, through: :hero_talents

  has_many :builds, inverse_of: :hero

  mount_uploader :image, ImageUploader
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]

  # GET /heros
  # GET /heros.json
  def index
    @heros = Hero.all
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros
  # POST /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Hero was successfully created.' }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: 'Hero was successfully updated.' }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url, notice: 'Hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:name, :hero_class, :description, :image)            
                                                                    
    end
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/views/heros/_form.html.erb
<div class='row'>
  <%= form_with(model: hero, local: true, :html => {:multipart => true}, class: 'form-horizontal form-material') do |form| %>
    <div class="col-md-4 col-xs-12">
      <div class="white-box">
        <div class="user-bg">
          <img width="100%" alt="user" src="../plugins/images/large/img1.jpg">
          <div class="overlay-box">
            <div class="user-content">
              <a href="javascript:void(0)">
                <%= image_tag hero.image_url(:thumb), class: 'thumb-lg img-circle' if hero.image? %>
              </a>
              <h4 class="text-white"><%= hero.name %></h4>
              <div class="text-center">
                <div class="col-sm-8 col-sm-offset-2">
                  <%= form.file_field :image %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-8 col-xs-12">
      <div class="white-box">
        
        <div class="form-group">
          <%= form.label :name, class: 'col-sm-12' %>
          <div class="col-sm-12">
            <%= form.text_field :name, class: 'form-control form-control-line', placeholder: 'Name' %>
          </div>
        </div>
            
        <div class="form-group">
          <%= form.label :hero_class, class: 'col-sm-12' %>
          <div class="col-sm-12">
            <%= form.text_field :hero_class, class: 'form-control form-control-line', placeholder: 'Class' %>
          </div>
        </div>

        <div class="form-group">
          <%= form.label :description, class: 'col-sm-12' %>
          <div class="col-sm-12">
            <%= form.text_area :description, class: 'form-control form-control-line', placeholder: 'Description' %>
          </div>
        </div>
        
        <div class="form-group">
          <div class="col-sm-12">
            <button class="btn btn-success" type="submit">Submit</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/heros/edit.html.erb
<%= render "layouts/page_title" %>
<%= render 'form', hero: @hero %>
<%= link_to 'Back', heros_path %>

app/views/heros/index.html.erb
<%= render "layouts/page_title" %>
<div class='row'>
  <div class='col-xs-12 text-right'>
    <%= link_to 'New Hero', new_hero_path, class: 'btn btn-sm btn-primary' %> 
  </div>
  <% @heros.each do |hero| %>
    <div class="col-sm-3">
      <div class="thumbnail">
        <%= image_tag hero.image_url(:thumb), class: 'thumb-lg img-circle' if hero.image? %>
        <div class="caption text-center">
          <h4 class='text-center'><%= hero.name %></h4>
          <p>
            <%= link_to 'View', hero, class: 'btn btn-sm btn-primary' %>
            <%= link_to 'Edit', edit_hero_path(hero), class: 'btn btn-sm btn-default' %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/heros/new.html.erb
<%= render "layouts/page_title" %>
<%= render 'form', hero: @hero %>
<%= link_to 'Back', heros_path %>

app/views/heros/show.html.erb
<%= render "layouts/page_title" %>

<div class='row'>
  <div class="col-md-4 col-xs-12">
    <div class="white-box">
      <div class="user-bg">
        <div class="overlay-box">
          <div class="user-content">
            <a href="javascript:void(0)">
              <%= image_tag @hero.image_url(:thumb), class: 'thumb-lg img-circle' if @hero.image? %>
            </a>
            <h4 class="text-white">
              <%= @hero.name %>
              <small>Class: <%= @hero.hero_class %></small>    
            </h4>
          </div>
        </div>
      </div>
      <div class="user-btm-box">
        <div class="col-sm-12 text-center">
          <p class="text-purple"><%= simple_format @hero.description %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-8 col-xs-12">
    <div class="white-box">
      <div class="row">
        <h3>Talents:</h3>
        <% @hero.talents.each do |talent| %>
          <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
              <%= image_tag talent.image_url(:thumb), class: 'thumb-lg img-circle' if talent.image? %>
              <div class="caption">
                <h4 class='text-center'><%= talent.name %></h4>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>