config/routes.rb
Rails.application.routes.draw do
  resources :builds
  root to: "home#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :maps
  resources :talents
  resources :heros
end

app/models/map.rb
class Map < ApplicationRecord
  has_many :build_maps
  has_many :builds, through: :build_maps

  mount_uploader :image, ImageUploader
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:name, :description, :image)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<div class='row'>
  <%= form_with(model: map, local: true, class: 'form-horizontal form-material') do |form| %>
    <div class="col-md-4 col-xs-12">
      <div class="white-box">
        <div class="user-bg">
          <%= image_tag map.image_url(:thumb), width: '100%' if map.image? %>
          <div class="overlay-box">
            <div class="user-content">
              <h4 class="text-white"><%= map.name %></h4>
              <div class="text-center">
                <div class="col-sm-8 col-sm-offset-2">
                  <%= form.file_field :image %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-8 col-xs-12">
      <div class="white-box">
        <div class="form-group">
          <%= form.label :name, class: 'col-sm-12' %>
          <div class="col-sm-12">
            <%= form.text_field :name, class: 'form-control', placeholder: 'Name' %>
          </div>
        </div>

        <div class="form-group">
          <%= form.label :description, class: 'col-sm-12' %>
          <div class="col-sm-12">
            <%= form.text_area :description, class: 'form-control form-control-line', placeholder: 'Information' %>
          </div>
        </div>
        
        <div class="form-group">
          <div class="col-sm-12">
            <button class="btn btn-success" type="submit">Submit</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/maps/edit.html.erb
<%= render "layouts/page_title" %>

<%= render 'form', map: @map %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<%= render "layouts/page_title" %>
<div class='row'>
  <div class='col-xs-12 text-right'>
    <%= link_to 'New Map', new_map_path, class: 'btn btn-sm btn-primary' %> 
  </div>
  <% @maps.each do |map| %>
    <div class="col-sm-3">
      <div class="thumbnail">
        <%= image_tag map.image_url(:thumb), class: 'thumb-lg img-circle' if map.image? %>
        <div class="caption text-center">
          <h4 class='text-center'><%= map.name %></h4>
          <p>
            <%= link_to 'View', map, class: 'btn btn-sm btn-primary' %>
            <%= link_to 'Edit', edit_map_path(map), class: 'btn btn-sm btn-default' %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div> 

app/views/maps/new.html.erb
<%= render "layouts/page_title" %>

<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<%= render "layouts/page_title" %>

<div class='row'>
  <div class="col-md-8 col-md-offset-2 col-xs-12">
    <div class="white-box">
      <h2><%= @map.name %></h2>
      <%= image_tag @map.image_url(:thumb), width: '100%' if @map.image? %>
      <div class="user-btm-box">
        <div class="col-sm-12 text-center">
          <p class="text-purple"><%= simple_format @map.description %></p>
        </div>
      </div>
    </div>
  </div>
</div>