config/routes.rb
Rails.application.routes.draw do
  resources :builds
  root to: "home#index"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :maps
  resources :talents
  resources :heros
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/build.rb
class Build < ApplicationRecord
  has_many :build_talents, inverse_of: :build, dependent: :destroy
  has_many :talents, through: :build_talents

  has_many :build_maps, inverse_of: :build, dependent: :destroy
  has_many :maps, through: :build_maps

  has_many :counters, inverse_of: :build
  has_many :counter_heros, through: :counters, source: :hero

  has_many :synergies, inverse_of: :build
  has_many :synergy_heros, through: :synergies, source: :hero

  belongs_to :hero

  mount_uploader :image, ImageUploader
end

app/models/build_hero.rb
class BuildHero < ApplicationRecord
  belongs_to :build
  belongs_to :hero
end

app/models/build_map.rb
class BuildMap < ApplicationRecord
  belongs_to :build 
  belongs_to :map 

  validates :build, presence: true
end

app/models/build_talent.rb
class BuildTalent < ApplicationRecord
  belongs_to :build 
  belongs_to :talent 
end

app/models/counter.rb
class Counter < BuildHero
end

app/models/hero.rb
class Hero < ApplicationRecord
  has_many :hero_talents, inverse_of: :hero
  has_many :talents, through: :hero_talents

  has_many :builds, inverse_of: :hero

  mount_uploader :image, ImageUploader
end

app/models/hero_talent.rb
class HeroTalent < ApplicationRecord
  belongs_to :hero
  belongs_to :talent
end

app/models/map.rb
class Map < ApplicationRecord
  has_many :build_maps
  has_many :builds, through: :build_maps

  mount_uploader :image, ImageUploader
end

app/models/synergy.rb
class Synergy < BuildHero
end

app/models/talent.rb
class Talent < ApplicationRecord
  has_many :hero_talents, inverse_of: :talent
  has_many :heros, through: :hero_talents

  has_many :build_talents, inverse_of: :talent
  has_many :builds, through: :build_talents

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]

  # GET /heros
  # GET /heros.json
  def index
    @heros = Hero.all
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros
  # POST /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Hero was successfully created.' }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: 'Hero was successfully updated.' }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url, notice: 'Hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:name, :hero_class, :description, :image)            
                                                                    
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:name, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/views/layouts/_page_title.html.erb
<div class="row bg-title">
  <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
    <h4 class="page-title">
      <%= "#{controller.action_name.titleize} #{controller.controller_name.titleize}" %>
    </h4> 
  </div>
  <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
    <ol class="breadcrumb">
      <li><a href="#"><%= controller.controller_name.titleize %></a></li>
    </ol>
  </div>
</div>

app/views/layouts/_side_nav.html.erb
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse slimscrollsidebar">
    <ul class="nav" id="side-menu">
      <li style="padding: 10px 0 0;">
        <a href="index.html" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Dashboard</span></a>
      </li>
      <li>
        <%= link_to builds_path, class: 'active' do%>
          <i class='fa fa-building fa-fw'></i>
          <span class="hide-menu">Builds</span>
        <% end %>
      </li>

      <li>
        <%= link_to heros_path, class: '' do%>
          <i class='fa fa-superpowers fa-fw'></i>
          <span class="hide-menu">Heros</span>
        <% end %>
      </li>
      <li>
        <%= link_to talents_path, class: '' do%>
          <i class='fa fa-tree fa-fw'></i>
          <span class="hide-menu">Talents</span>
        <% end %>
      </li> 
      <li>
        <%= link_to maps_path, class: '' do%>
          <i class='fa fa-map fa-fw'></i>
          <span class="hide-menu">Maps</span>
        <% end %>
      </li>                  
    </ul>
  </div>
</div>

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-default navbar-static-top m-b-0">
  <div class="navbar-header"> <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse"><i class="fa fa-bars"></i></a>
      <div class="top-left-part"><a class="logo" href="index.html"><b><img src="../plugins/images/pixeladmin-logo.png" alt="HoS" /></b><span class="hidden-xs"><img src="../plugins/images/pixeladmin-text.png" alt="Architect" /></span></a></div>
      <ul class="nav navbar-top-links navbar-left m-l-20 hidden-xs">
          <li>
              <form role="search" class="app-search hidden-xs">
                  <input type="text" placeholder="Search..." class="form-control"> <a href=""><i class="fa fa-search"></i></a>
              </form>
          </li>
      </ul>
  </div>
  <!-- /.navbar-header -->
  <!-- /.navbar-top-links -->
  <!-- /.navbar-static-side -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <div class="preloader">
      <div class="cssload-speeding-wheel"></div>
    </div> -->
    <div id="wrapper">
      <%= render "layouts/top_nav" %>
      <%= render "layouts/side_nav" %>
      <div id="page-wrapper">
        <div class="container-fluid">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>